### ISSUE TITLE
Implement Typewriter Animation on Hero Section of Website

### ISSUE THREAD

**Issue by gabenavarro** [gabenavarro/gabriel-navarro-bio#1]
**Description:**  
We want to enhance the visual impact of the hero section on the landing page by implementing a **CSS-only typewriter effect** that types out multiple lines of engaging text. The animation should simulate a typing experience with a blinking cursor and sequentially reveal three different lines of copy.

---

**Acceptance Criteria:**

- [ ] The hero section displays **three lines of text**, each appearing with a smooth typewriter animation.
- [ ] The animation plays **in sequence**:
  1. First line types out completely.
  2. Second line appears after a short delay.
  3. Third line animates with a blinking cursor effect.
- [ ] All animations should be handled **purely with CSS** (no JS required).
- [ ] The text cursor (border-right) should **blink** at the end of the last line.
- [ ] The text should use a **monospace font** like Courier and remain accessible.
- [ ] Mobile and desktop views should maintain legibility and animation fluidity.

---

**Implementation Notes:**

- Use the following CSS as the base (can be refactored for clarity or modularity):

```css
.css-typing p {
  border-right: .15em solid orange;
  font-family: "Courier";
  font-size: 14px;
  white-space: nowrap;
  overflow: hidden;
}
/* First line */
.css-typing p:nth-child(1) {
  width: 7.3em;
  animation: type 2s steps(40, end) forwards;
}
/* Second line */
.css-typing p:nth-child(2) {
  width: 11.5em;
  opacity: 0;
  animation: type2 2s steps(40, end) 2s forwards;
}
/* Third line */
.css-typing p:nth-child(3) {
  width: 7.3em;
  opacity: 0;
  animation: type3 5s steps(20, end) 4s forwards, blink 0.5s step-end infinite alternate 9s;
}
@keyframes type { 0% { width: 0 } 99.9% { border-right: .15em solid orange } 100% { border: none } }
@keyframes type2 { 0% { width: 0 } 1% { opacity: 1 } 100% { opacity: 1; border: none } }
@keyframes type3 { 0% { width: 0 } 1% { opacity: 1 } 100% { opacity: 1 } }
@keyframes blink { 50% { border-color: transparent } }
```

---

**QA Notes:**

- Test on Chrome, Firefox, Safari.
- Ensure animation respects user `prefers-reduced-motion` setting (optional, bonus points).
