### ISSUE TITLE
Implement Native Scroll-Based Animation on Hero Page Achievements Using

### ISSUE THREAD

**Issue by gabenavarro** [gabenavarro/gabriel-navarro-bio#2]
**Description:**  
To enhance the visual professionalism and interactivity of the Hero section, we want to implement a native **"Animate on Scroll"** effect using `IntersectionObserver` in JavaScript combined with smooth CSS transitions. This will animate the **Achievements section** elements as they enter or leave the viewport during scroll, improving user engagement and providing a modern UI feel without relying on third-party libraries.

---

**Scope of Work:**

- [ ] Apply `IntersectionObserver` to target all `.hidden` achievement elements within the Hero section.
- [ ] Toggle a `.show` class that triggers a CSS transition and transform animation (`translateX`, `blur`, and `opacity`).
- [ ] Ensure animations feel smooth and polished (duration: ~1s).
- [ ] Gracefully animate out of view when scrolling away (remove `.show`).
- [ ] Respect `prefers-reduced-motion` media query for accessibility and reduced motion preferences.

---

**Technical Reference (CSS + JS):**

**CSS**
```css
.hidden {
  opacity: 0;
  filter: blur(5px);
  transform: translateX(-100%);
  transition: all 1s ease;
}

.show {
  opacity: 1;
  filter: blur(0);
  transform: translateX(0);
}

@media (prefers-reduced-motion) {
  .hidden {
    transition: none;
  }
}
```

**JavaScript**
```js
const observer = new IntersectionObserver((entries) => {
  entries.forEach((entry) => {
    if (entry.isIntersecting) {
      entry.target.classList.add('show');
    } else {
      entry.target.classList.remove('show');
    }
  });
});

const hiddenElements = document.querySelectorAll('.hidden');
hiddenElements.forEach((el) => observer.observe(el));
```

---

**Acceptance Criteria:**

- [ ] Hero Achievements section elements smoothly slide in from the left as they enter viewport.
- [ ] Elements blur in and fade from opacity 0 to 1.
- [ ] On scroll out, elements revert to hidden state (if required for repeat).
- [ ] Animations are disabled when user has `prefers-reduced-motion` enabled.
- [ ] Behavior works consistently across Chrome, Firefox, Safari, and mobile browsers.

---

**Design Note:**  
Mockups not needed; behavior can be verified visually using scroll on Hero section.
