### ISSUE TITLE
Fix Mobile Horizontal Overflow

### ISSUE THREAD

**Issue by gabenavarro** [gabenavarro/gabriel-navarro-bio#45]
### **Summary**
Currently, the site exhibits unwanted **horizontal scrolling (overflow-x)** on mobile devices.  
This ticket proposes a clean CSS solution to fully eliminate the overflow issue while maintaining smooth animations and responsive design.

---

### **Proposed CSS Fixes**

```css
/* Global box-sizing to respect width constraints */
* {
  box-sizing: border-box;
  max-width: 100vw;
}

/* Container constraints */
.container {
  width: 100%;
  max-width: var(--container-max-width);
  margin: 0 auto;
  position: relative;
  z-index: 2;
  padding: 0 1rem;
  padding-bottom: 2rem;
  overflow-x: hidden; /* New */
}

/* Scroll animation fixes */
.scroll-right-hidden,
.scroll-left-hidden {
  width: 100%;
  max-width: 100%;
  transform: translateX(30%); /* Reduced from 100% */
}

.scroll-left-hidden {
  transform: translateX(-30%); /* Reduced from -100% */
}

/* Mobile-specific overflow control */
@media (max-width: 768px) {
  body {
    position: relative;
    width: 100%;
    overflow-x: hidden;
  }

  h1, h2, h3, p {
    max-width: 100%;
    word-wrap: break-word;
  }

  img, video, iframe {
    max-width: 100%;
    height: auto;
  }
}
```

---

### **Why This Matters**
✅ Eliminates ugly side-scrolling on mobile  
✅ Improves UX and visual consistency  
✅ Prepares app for better SEO and Core Web Vitals scores (especially for mobile-first indexing)

---

### **Acceptance Criteria**
- [ ] No horizontal scrollbars on mobile devices (tested at various screen sizes).
- [ ] All text, images, and buttons remain properly sized and centered.
- [ ] Scroll-in animations (`scroll-left-hidden`, `scroll-right-hidden`) continue to work cleanly.

---

### **Suggested Next Steps**
- Patch the main base CSS file (`src/lib/css/base.py`).
- Test visually across desktop, tablet, and phone breakpoints.
- Deploy update to preview branch for QA testing.
