### ISSUE TITLE
Masonry height scrolling fix

### ISSUE THREAD

**Issue by gabenavarro** [gabenavarro/gabriel-navarro-bio#64]
## Description:
There's an issue with the masonry layout on the portfolio page where a vertical scrollbar temporarily appears when selecting or deselecting category filter chips (Machine Learning, Omics, etc.). This creates an unintended "jumping" effect that negatively impacts user experience.

## Bug Details
- When clicking on filter chips to show/hide content, a vertical scrollbar briefly appears and then disappears
- This causes the layout to shift horizontally by the width of the scrollbar
- The issue is visible in the attached screenshot where the scrollbar appears during filter transitions

## Technical Analysis
The issue appears to be related to how the masonry container's height is calculated during filtering operations. The `.masonry-container` has `min-height: 100vh` which may be contributing to the problem.

## Suggested Fixes
1. Use `overflow-y: scroll` with a matching padding-right to always show scrollbar:
   ```css
   .masonry-container {
     overflow-y: scroll;
     padding-right: calc(1rem + 17px); /* Compensate for scrollbar width */
   }
   ```

2. Alternative approach - prevent layout shifts by forcing scrollbar visibility:
   ```css
   html {
     overflow-y: scroll; /* Always show scrollbar */
   }
   ```

3. Add a height transition to smooth the height changes:
   ```css
   .masonry-container {
     transition: height 0.3s ease;
   }
   ```

4. Fix the root issue by improving the masonry recalculation:
   - Ensure height calculations happen after filtering is complete
   - Implement a better masonry library or custom solution that properly handles height transitions
   - Consider using CSS Grid with `grid-template-rows: masonry` for modern browsers

## Steps to Reproduce
1. Load the portfolio page
2. Click on any category filter chip (e.g., "Machine Learning")
3. Quickly click on another filter or deselect the current one
4. Notice the brief appearance of a vertical scrollbar and layout shift

## Priority
Medium - This is a visual issue that affects user experience but doesn't break functionality

## Acceptance Criteria
- No vertical scrollbar should appear or disappear during filter operations
- The layout should not shift horizontally when applying filters
- The transition between filtered states should be smooth

## Environment
- Latest Chrome, Firefox, and Safari browsers
- Desktop and mobile viewports

![Image](https://github.com/user-attachments/assets/7895721b-d7df-462c-b216-ae75067fa86d)
